//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int id_doctor { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public Nullable<int> hours { get; set; }
        public string login { get; set; }
        public string pas { get; set; }
    }
}
