//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class otchet_zp
    {
        public int id_ozp { get; set; }
        public int id_doctor { get; set; }
        public System.DateTime data_ozp { get; set; }
        public int hours { get; set; }
        public Nullable<int> zp { get; set; }
        public string description { get; set; }
    }
}
